version: "2"

services:
    ipfsnode:
        image: ipfs/go-ipfs
        restart: always
        volumes:
            - ~/volumes/ipfs:/data/ipfs
        ports:
            - "4001:4001"
    frontend:
        build: .
        restart: always
        volumes:
            - /tmp/letsencrypt-auto:/tmp/letsencrypt-auto
        ports:
            - "80:80"
            - "443:443"
